name: Reusable Checkov Terraform Scan job workflow

on:
  workflow_call:
    inputs:
      projectdir:
        required: true
        type: string 

jobs:
  checkov_terraform_scan_job:
    name: Checkov Terraform Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform
          framework: terraform 
