name: Reusable Checkov Terraform Scan job workflow

on:
  workflow_call:
    inputs:
      projectdir:
        required: true
        type: string 
      softfail:
        required : true
        type: boolean

jobs:
  checkov_terraform_scan_job:
    name: Checkov Terraform Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # name: Set up Python 3.8
      # uses: actions/setup-python@v1
      # with:
      #   python-version: 3.8
      #- name: Test with Checkov
      #  id: checkov
      #  uses: bridgecrewio/checkov-action@master
      #  with:
      #    directory: ${{ inputs.projectdir }}
      #    framework: terraform 
      #    soft_fail: ${{ inputs.softfail }}
      #    output_format: junitxml
      #- name: checkov result
      #  run: echo "${{ steps.checkov.outputs.results }}" >> result1.xml 
      - name: print
        run: |
         echo "test sgsdgsadsg test" >> result2.txt
         printf "${{ result2.txt }}"
         echo "fainal te3ste"
      #- name: grep  
      #  run: sed '1,7d' result1.xml
      #- name: print  
      #  run: printf $result1.xml
      #- name: docker job 1
      #  run: docker pull bridgecrew/checkov
      #- name: docker job 2  
      #  run: docker run --volume $(pwd):/tf bridgecrew/checkov --directory infra --output junitxml --soft-fail > $(pwd)/CheckovReport.xml
      #- name: docker job 3  
      #  run: printf $(pwd)/CheckovReport.xml
      #- name: Publish Test Results
      #  uses: mikepenz/action-junit-report@v3
      #  if: always()
      #  with:
      #   report_paths: $(pwd)/CheckovReport.xml
