name: Reusable Sonarcloud Analysis job workflow

on:
  workflow_call:
    inputs:
      projectdir:
        required: true
        type: string
    secrets:
      sonartoken:
        required: true      

jobs:
  sonarcloud_analysis_job:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: backend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.sonartoken }}
