name: Reusable Trivy scan job workflow
on:
  workflow_call:
    inputs:
      imagename:
        required: true
        type: string
      projectname:
        required: true
        type: string
      scanstatus:
        required: true
        type: string        
    secrets:
      awskeyid:
        required: true
      awskeysecret:
        required: true       
jobs:
 trivy_scan_job:
    name: Trivy container scan job
    runs-on: ubuntu-latest
    container: docker.io/aquasec/trivy:latest    
    steps:  
      - uses: actions/checkout@v2
      #- uses: actions/setup-python@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.awskeyid }}
          aws-secret-access-key: ${{ secrets.awskeysecret }}
          aws-region: "eu-west-2"
          mask-aws-account-id: "no"
      - run: |
          trivy image -f json -o report.json "${{ inputs.imagename }}"
          #pip install requests
          #python import.py "Trivy Scan" "${{ inputs.scanstatus }}" "report.json" "${{ inputs.projectname }}"
      - uses: actions/upload-artifact@v3
        with:
         name: my-artifact
         path: report.json
 trivy_scan_job1:
    name: Trivy container scan job1
    needs: trivy_scan_job
    runs-on: ubuntu-latest
    #container: docker.io/aquasec/trivy:latest    
    steps:  
      - uses: actions/checkout@v2         
      - uses: actions/download-artifact@v3
        #with:
          #name: my-artifact
          #path: path/to/artifact
    
      - name: Display structure of downloaded files
        run: ls -R
        #working-directory: path/to/artifact
