name: Reusable Trivy scan job workflow

on:
  workflow_call:
    inputs:
      imagename:
        required: true
        type: string
    secrets:
      awskeyid:
        required: true
      awskeysecret:
        required: true
        

jobs:
  trivy_scan_job:
    name: Trivy container scan job
    runs-on: ubuntu-latest
    container: docker.io/aquasec/trivy:latest    
    steps:  
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.awskeyid }}
          aws-secret-access-key: ${{ secrets.awskeysecret }}
          aws-region: "eu-west-2"
          mask-aws-account-id: "no"
      - name: Trivy Scan
        run: |
          trivy image -f json -o report.json "${{ inputs.imagename }}"  
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: execute py script 
        run: |
          python import.py
